### ISSUE TITLE
Publish the content to Github pages?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/ui-best-practices#2]
With a gtihub page it is even possible to get a nice domain like: https://ux-guide.eclipseprojects.io/ .. just open a [Help Desk Issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues)!

**Comment by laeubi** [comment]
Here is an example to publish content with asciidoctor to gh pages: https://github.com/marketplace/actions/build-asciidoctor-action

**Comment by laeubi** [comment]
@guw @azoitl can you probably look into this?

**Comment by guw** [comment]
I don't think the group is still active. Contributors wanted, though.

**Comment by azoitl** [comment]
I can try to support here. @guw did you close this issue on purpose?

**Comment by laeubi** [comment]
> I don't think the group is still active. Contributors wanted, though.

DO you think closed tickets will attract contributions?

**Comment by guw** [comment]
Frankly, I don't think there is interest in keeping this running. There has been zero contributions in the last six years and no-one really missed it. In terms of Eclipse this should have been archived long time ago.

**Comment by azoitl** [comment]
@guw I find your reaction interesting. I observed the original move to github and had planned to support. But as so often things on my side changed and I was not able to. Now that several people here and in different mailing lists show again interest you are totally blocking their interest. Very strange.

**Comment by guw** [comment]
Oh, I am not blocking it. I may have been too realistic. :) If anyone wants to contribute please to so with PRs. Happy to review and merge any.

**Comment by azoitl** [comment]
Then I may have misunderstood you. I created some pullrequests today. With them the ascidoc version (at least how github directly shows them) should already be in a more or less usable state.

**Comment by laeubi** [comment]
Could the issue be reopened?
I created: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2416 it just needs a +1 from one of the project leads.

**Comment by laeubi** [comment]
@vogella I think that was too optimistic, so I reopen this, the build complains about:

`asciidoctor: FAILED: input file docs/index.adoc is missing`

@azoitl this should probabbly be [eclipse_ui_guidelines.adoc](https://github.com/eclipse-platform/ui-best-practices/blob/main/eclipse_ui_guidelines.adoc) right?

**Comment by azoitl** [comment]
> @vogella I think that was too optimistic, so I reopen this, the build complains about:
> 
> `asciidoctor: FAILED: input file docs/index.adoc is missing`
> 
> @azoitl this should probabbly be [eclipse_ui_guidelines.adoc](https://github.com/eclipse-platform/ui-best-practices/blob/main/eclipse_ui_guidelines.adoc) right?

Yes currently this is our main file. I was also thinking if we should rename this file. But please let us do this after my PRs are merged. Will fix the merge conflicts ASAP.

**Comment by laeubi** [comment]
Alright, can you adjust the workflow to whatever you think is most suitable afterwards?

**Comment by azoitl** [comment]
> Alright, can you adjust the workflow to whatever you think is most suitable afterwards?

As my changes are now all merged I would target that as next step. As part of the clean-up I split the main content in individual files. Therefore I think we should rename our main file [eclipse_ui_guidelines.adoc](https://github.com/eclipse-platform/ui-best-practices/blob/main/eclipse_ui_guidelines.adoc) to something better indicating that it is the root file. Should it be main.adoc or index.adoc? After that change I would merge main to the gh_pages branch and fix the yml script.

**Comment by laeubi** [comment]
> Therefore I think we should rename our main file [eclipse_ui_guidelines.adoc](https://github.com/eclipse-platform/ui-best-practices/blob/main/eclipse_ui_guidelines.adoc) to something better indicating that it is the root file. Should it be main.adoc or index.adoc?

Whatever you think suffice!

> After that change I would merge main to the gh_pages branch and fix the yml script.

Nothing needs to be merged to `gh_pages`! This is a special branch that will hold the generated html but this is created from the main branch and just the result is pushed there!

So simply adjust the yml file (on main branch) and then all should be fine!

**Comment by vogella** [comment]
index.adoc sounds good

**Comment by azoitl** [comment]
updated index.adoc and publish.yml hope this works now.

**Comment by azoitl** [comment]
Does it work now? I think I'm to dumb to find the output. Where do I find the resulting gh page?

**Comment by laeubi** [comment]
You can find all runs here: https://github.com/eclipse-platform/ui-best-practices/actions currently I'm struggling with gettting the result deployed ...

**Comment by laeubi** [comment]
Finally! 
https://github.com/eclipse-platform/ui-best-practices/tree/gh-pages

https://eclipse-platform.github.io/ui-best-practices/

**Comment by vogella** [comment]
How to we expect people to find this if it is not mentioned in the readme? If will open PR to add a link to the readme.

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/211548638-21855207-be26-4fb6-82e9-a439d3959e2a.png)
