### ISSUE TITLE
Links in deployed variant do not work

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/ui-best-practices#21]
See https://eclipse-platform.github.io/ui-best-practices/ and click on a link > 404 

For example:

https://eclipse-platform.github.io/ui-best-practices/top_ten_lists.adoc

but replace the file ending with `.html` works:
https://eclipse-platform.github.io/ui-best-practices/top_ten_lists.html

@azoitl can you suggest a fix for this? can ascidoctor instructed to replace these `.adoc` with `.html` when generating content?

**Comment by laeubi** [comment]
It also seems the images folder is not copied to the docs folder used for output ...

**Comment by azoitl** [comment]
> See https://eclipse-platform.github.io/ui-best-practices/ and click on a link > 404
> 
> For example:
> 
> https://eclipse-platform.github.io/ui-best-practices/top_ten_lists.adoc
> 
> but replace the file ending with `.html` works: https://eclipse-platform.github.io/ui-best-practices/top_ten_lists.html
> 
> @azoitl can you suggest a fix for this? can ascidoctor instructed to replace these `.adoc` with `.html` when generating content?

I can give it a try later today. need to google a bit.

**Comment by azoitl** [comment]
@laeubi I found the solution for the link. 

**For documentation purposes:** I should have used the xref macro instead of the link macro. 

Will fix it in the next minutes.

**Comment by azoitl** [comment]
Please not that still many links are broken. This will be a longer work to fix them. I hope I find some time in the next days/weeks to go through each file.

**Comment by azoitl** [comment]
Just to be clear these are old links from the wiki conversion or which where broken already in the wiki.

**Comment by BeckerWdf** [comment]
If you provide a list of broken links I could help here.

**Comment by Bananeweizen** [comment]
I've checked several dozen links starting from the top and they all work. Assuming this has been fixed in the past. Please create new issues for specific links that still don't work.
