### ISSUE TITLE
build via asciidoctor-maven-plugin

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/ui-best-practices#23]
Assuming that most people looking into these UI guidelines are in fact Java developers, shouldn't we convert this to a simple Maven project, and run the Asciidoc processing via asciidoctor-maven-plugin? I assume that would allow more people to run a local build (e.g. I don't know what to do with the makefile on my Windows machine, honestly).

Shall I create a simple POM for that? Does that somehow interfere with the github actions based build?

**Comment by laeubi** [comment]
I think the best is to create a PR to show how it looks like (probably one could even have makefile+pom?)

>  Does that somehow interfere with the github actions based build?

This was just a naive attempt, if we can do the same with maven it might even be simpler than a "real" asciidoctor call in a custom container...

**Comment by laeubi** [comment]
This is now merged and the build is adjusted.
Thanks for providing this, this runs much faster!

**Comment by azoitl** [comment]
@Bananeweizen I just noticed that the figures are not shown anymore in the deployed docs. Any idea what went wrong here.

**Comment by Bananeweizen** [comment]
@azoitl Fixed it. When you added the resource entry for the media folder, you created a second `resources` block instead of just a second nested `resource` entry. Since the Maven plugin gets the content of the resources block injected as member fields from the surrounding Maven tooling, it had only the new media folder as resources.
I'll check if an improvement can be done on the Asciidoctor Maven plugin side to better declare the allowed configuration (and have the POM editor raise a warning then for a wrong config entry).

**Comment by azoitl** [comment]
@Bananeweizen I just saw your fix of my stupidness a minute ago. I mostly use pomless tycho so my maven knowledge is very low. May should change that.
