### ISSUE TITLE
Github workflows affect forks

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/ui-best-practices#28]
When trying to push a branch to my personal fork, I get the below error message in egit:
```
Repository https://github.com/Bananeweizen/ui-best-practices.git

refusing to allow a Personal Access Token to create or update workflow `.github/workflows/publish.yml` without `workflow` scope
```
I guess this is because the fork also contains the `.github/foo.yml` files. I have no idea what needs to be done to avoid that, but I'm sure we are not the first repository where people want to enable workflows in the main repo, but not in its forks. Be aware that I use a personal access token with very restricted scope, so I could probably avoid this by enlarging my token. However, my preferred solution would rather be to somehow make the workflows really only available in the main repo.

Anyone else with better knowledge of github actions?

**Comment by vogella** [comment]
You need to generate a GH developer token with the workflow permission

**Comment by vogella** [comment]
Alternatively you can IIRC disable GH actions for your fork

**Comment by laeubi** [comment]
Just go to settings > action > disable > save

**Comment by Bananeweizen** [comment]
Thanks for all the hints, I probably never visited those settings before. In the end, the settings didn't affect the push, so I modified the token instead. In fact, the UI suggested to add the workflow checkbox for the existing token, so they probably realized that the "repo" only tokens are not that useful.
