### ISSUE TITLE
Downloads refer to the github repository

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/ui-best-practices#33]
Saerch in the document for "Download the palette"
Then click on any of the links.

> You can download the palette in the [".aco"](https://github.com/eclipse-platform/eclipse.platform.images/tree/master/org.eclipse.images/tools/eclipse-style_palette.aco), [".ai"](https://github.com/eclipse-platform/eclipse.platform.images/tree/master/org.eclipse.images/tools/eclipse-style_palette.ai), and [".gpl"](https://github.com/eclipse-platform/eclipse.platform.images/tree/master/org.eclipse.images/tools/eclipse-style_palette.gpl) file format.

This will redirect to github and the user has to choose further actions (e.g choose "raw") to actually download the stuff. It would bee good (as with the images) to actually embeds these into the site content in a way that a direct download is triggered and that is not referring to gtihub content directly so these are part of the regular deployment.

**Comment by Bananeweizen** [comment]
You probably want to copy that file to the "media" folder and change the link to be a relative link (with the raw parameter). That should be sufficient.
