### ISSUE TITLE
Spellchecker as Github action?

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/ui-best-practices#39]
Anyone aware of a automatic spell checker for Asciidoc? Would be very cool to have such a GH action  for incoming pull requests.

**Comment by Bananeweizen** [comment]
I edit in Eclipse, thereby getting the Eclipse spell checker underline markers. I'm not aware of an automation that is actually good enough to not throw way too many false positives, because it doesn't get what's actual text and what not (Asciidoc macros, anchor names, paths, ....)

**Comment by vogella** [comment]
Thanks for the info @Bananeweizen
