### ISSUE TITLE
Most parts of the documents are not in the "One sentence per line" format

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/ui-best-practices#57]
Most parts of the documents are not in the "One sentence per line" format as it is described in the README.md file.
Should we fix this?

**Comment by Bananeweizen** [comment]
When we transferred the content to this repository, it contained a recommendation for fixed line lenghth of 80 characters. That is a bad recommendation nowadays, so I replaced it with what is really recommended for all kinds of markdown: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

I'm not aware of a simple way of reformatting automatically, without eventually changing the resulting rendering (e.g. you can write numbered lists as a series of ". text" lines, so dots have multiple meanings). I tend to reformat a paragraph whenever I change something, even though that makes the diff harder to evaluate. I'd be very happy to learn about other means of automatically normalizing/formatting asciidoc sources.

**Comment by vogella** [comment]
>  Should we fix this?

Yes, I typically do this in the part of documentation I do edit but if you want to do a "big update" that would be fine to me.
