### ISSUE TITLE
Please enable Github Discussions

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/ui-best-practices#8]
That way it would be much easier to ask questions or discuss things than with a mailing list:

https://docs.github.com/en/discussions/quickstart

If you don not have access to the settings, a helpdesk ticket would be required.

**Comment by vogella** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2430

**Comment by laeubi** [comment]
This seems to be enabled now!
