### ISSUE TITLE
Issue in 8.2.2 Multiple Item Selection

### ISSUE THREAD

**Issue by SchaergesWDF** [eclipse-platform/ui-best-practices#81]
The (fine) button order in the table is not matching with the (not fine) order in the example (image Cration Wizard of "Java Working Sets", there the guideline is not well used.  )
In the old guidelines (https://www.eclipse.org/articles/Article-UI-Guidelines/v200202/Index.html)
the example is fitting and usable

Also the corresponding updated Guideline 4.2 summarizing this is somehow corrupted _It should have the control buttons in this order: 'Add →', '', '_
Tail is cut.

**Comment by merks** [comment]
This repository hosts/renders its content here:

https://eclipse-platform.github.io/ui-best-practices/

We cannot fix decades old articles, but we can fix the content of this Git repository. 

Could you please describe the problem relative to the https://eclipse-platform.github.io/ui-best-practices/ content?

Note that it's easy to attach images to your problem report just by pasting the image into the browser's text control.  That should help make it more clear what exactly you are referring to.
